spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-management
          uri: lb://user-management
          predicates:
            - Path=/api/auth/**
          filters:
            - AddRequestHeader=X-Request-Foo, Bar

        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/v1/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/reservations/v1/**

        - id: cinema-service
          uri: lb://cinema-service
          predicates:
            - Path=/cinema/v1/**

app:
  jwt:
    secret: LnX1yH3pYq6gTbWxV2zQ8uRfNjKrI0VxTk6b2o4D4q9w2U5QjX
    expirationMs: 3600000

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
